#!/bin/bash

#LISTS POOLS TO ITERATE OVER

POOLCHECKER=($(zpool list | awk '{print $1}' | sed s/NAME//))

while true; do
for pool in "${POOLCHECKER[@]}"; do

#CHECKS FREE, ALLOACTED AND TOTAL SPACE AND USES AWK TO PRINT THE 2ND AND THIRD INTEGERS ENSURING THAT THERE ARE NO . IN ANY VALUES 

FREE=$(zpool iostat "$pool" | grep "$pool" | awk '{print int($3)}')
ALLOCATED=$(zpool iostat "$pool" | grep "$pool" | awk '{print int($2)}')
echo "$ALLOCATED"
TOTAL=$(echo "$ALLOCATED + $FREE" | bc | awk '{print int($1)}')
THRESHOLD=$(echo "0.80 * $TOTAL" | bc | awk '{print int($1)}')
echo "$THRESHOLD"
if [[ "$ALLOCATED" -gt "$THRESHOLD" ]]; then
echo "threshhold has been reached on $pool" >> ### path to log ###
echo "The 80% thresh hold has been reached on $pool, please rectify" | mail -s "THRESH HOLD" ### email address ###

#CONTINUE ENSURES EACH POOL IS ITERATED OVER

continue
else
echo "nothing to do"
continue
fi
done
sleep 3600
done
